[package]
name = "opteadm"
version = "0.2.0"

edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
# XXX For the time being opteadm needs to set the engine feature to
# get all the types. Once there types are move to their appropriate
# place this feature flag will be replaced/removed.
opte = { workspace = true, features = ["api", "engine", "std"] }
opte-ioctl.workspace = true
oxide-vpc = { workspace = true, features = ["api", "engine", "std"] }

anyhow.workspace = true
cfg-if.workspace = true
clap.workspace = true
libc.workspace = true
libnet.workspace = true
postcard.workspace = true
serde.workspace = true
thiserror.workspace = true

[build-dependencies]
anyhow.workspace = true
