// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Copyright 2024 Oxide Computer Company

// xde - A mac provider for OPTE-based network implementations.
#![feature(extern_types)]
#![feature(panic_info_message)]
#![no_std]
#![allow(non_upper_case_globals)]
// XXX We do not use double in the kernel. We should not allow
// "improper C types". This hack is here is because of the ip.rs code
// generated by bindgen. It brings in a bunch of stuff we do not use.
// At some point we could hand write the stuff that is actually
// needed, or come up with a better solution like using CTF data to
// generate Rust types for only the stuff we need.
#![allow(improper_ctypes)] // for long double -> u128
#![allow(non_camel_case_types)] // for bindgen code in ip.rs
#![allow(non_snake_case)] // for bindgen code in ip.rs
#![feature(alloc_error_handler)]
#![feature(rustc_private)]
#![deny(unused_must_use)]

mod ioctl;

#[macro_use]
extern crate alloc;

use core::alloc::Layout;

pub mod dls;
pub mod ip;
pub mod mac;
mod mac_sys;
pub mod route;
pub mod secpolicy;
pub mod sys;
pub mod xde;

// The GlobalAlloc is using KM_SLEEP; we can never hit this. However, the
// compiler forces us to define it, so we do.
#[alloc_error_handler]
fn alloc_error(_: Layout) -> ! {
    panic!("allocation error");
}

// This is a hack to get around the fact that liballoc includes
// calls to _Unwind_Resume, supposedly because it is not compiled
// with `panic=abort`. This is all a little bit beyond me but I just
// want to satisfy the symbol resolution so I can load this module.
//
// https://github.com/rust-lang/rust/issues/47493
#[allow(non_snake_case)]
#[no_mangle]
fn _Unwind_Resume() -> ! {
    panic!("_Unwind_Resume called");
}
