[package]
name = "xde-link"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
no-panics-whatsoever = "0.1.0"

[profile.dev]
panic = 'abort'

[profile.release]
panic = 'abort'
