[package]
name = "ctf"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
arrayref.workspace = true
flate2.workspace = true
num_enum.workspace = true
object.workspace = true